version: '3'
services: 
    jupyter:
        build: 
            context: ./docker/jupyter/
            dockerfile: Dockerfile
        image: kryvokhyzha/how-to-win-ds-competition:latest
        volumes: 
            - .:/home/jovyan/
        ports: 
            - "8888:8888"
        environment: 
            - JUPYTER_ENABLE_LAB=yes
